"""initial_neon_migration

Revision ID: 114c35c25bd9
Revises: 
Create Date: 2026-06-26 10:04:01.559856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '114c35c25bd9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop all old Prisma-managed tables with CASCADE to handle FK dependencies
    old_tables = [
        'payroll_runs', 'super_admin_products', 'time_entries', '"Organization"',
        'super_admin_system_health', 'super_admin_subscriptions', '"PayrollRun"',
        '"UserPermission"', '"Role"', 'invoices', '"GovernancePolicy"', 'report_runs',
        '"ComplianceReport"', '"Tenant"', '"ZoikoPayTransaction"', 'payslip_items',
        '"ApprovalWorkflow"', 'super_admin_audit_logs', '"UserRole"', '_prisma_migrations',
        'reports', 'super_admin_platform_settings', '"AuditLog"', 'policy_acknowledgements',
        '"ZoikoCoreXWorkflow"', 'compliance_policies', 'invoice_lines', '"ApprovalAction"',
        '"User"', 'super_admin_organization_products', 'clients', '"Subscription"',
        '"Session"', '"RolePermission"', '"Permission"',
    ]
    for table in old_tables:
        op.execute(f"DROP TABLE IF EXISTS {table} CASCADE")
    op.create_foreign_key(None, 'employees', 'employees', ['created_by'], ['id'])
    op.create_foreign_key(None, 'employees', 'employees', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_table('Permission',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tenantId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('domain', postgresql.ENUM('TENANTS', 'ORGANIZATIONS', 'USERS', 'PAYROLL', 'COMPLIANCE', 'BILLING', 'ANALYTICS', 'AUDIT', 'SYSTEM', name='PermissionDomain'), autoincrement=False, nullable=False),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenantId'], ['Tenant.id'], name='Permission_tenantId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='Permission_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('Permission_tenantId_key_key', 'Permission', ['tenantId', 'key'], unique=True)
    op.create_index('Permission_tenantId_idx', 'Permission', ['tenantId'], unique=False)
    op.create_index('Permission_domain_idx', 'Permission', ['domain'], unique=False)
    op.create_table('RolePermission',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tenantId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('roleId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('permissionId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('assignedAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permissionId'], ['Permission.id'], name='RolePermission_permissionId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['roleId'], ['Role.id'], name='RolePermission_roleId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='RolePermission_pkey')
    )
    op.create_index('RolePermission_tenantId_idx', 'RolePermission', ['tenantId'], unique=False)
    op.create_index('RolePermission_roleId_permissionId_key', 'RolePermission', ['roleId', 'permissionId'], unique=True)
    op.create_index('RolePermission_permissionId_idx', 'RolePermission', ['permissionId'], unique=False)
    op.create_table('Session',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tenantId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('refreshTokenHash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expiresAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('ipAddress', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('userAgent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('revokedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('accessTokenId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenantId'], ['Tenant.id'], name='Session_tenantId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name='Session_userId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='Session_pkey')
    )
    op.create_index('Session_userId_idx', 'Session', ['userId'], unique=False)
    op.create_index('Session_tenantId_idx', 'Session', ['tenantId'], unique=False)
    op.create_index('Session_expiresAt_idx', 'Session', ['expiresAt'], unique=False)
    op.create_index('Session_accessTokenId_key', 'Session', ['accessTokenId'], unique=True)
    op.create_table('Subscription',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tenantId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('product', postgresql.ENUM('ZOIKO_HR', 'ZOIKO_TIME', 'ZOIKO_PAYROLL', 'ZOIKO_BILLING', 'ZOIKO_COMPLY', 'ZOIKO_INSIGHTS', name='ZoikoProduct'), autoincrement=False, nullable=False),
    sa.Column('plan', postgresql.ENUM('TRIAL', 'PREMIUM', 'ENTERPRISE', name='Plan'), server_default=sa.text('\'ENTERPRISE\'::"Plan"'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'TRIALING', 'PAST_DUE', 'SUSPENDED', 'CANCELED', name='SubscriptionStatus'), server_default=sa.text('\'ACTIVE\'::"SubscriptionStatus"'), autoincrement=False, nullable=False),
    sa.Column('seats', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('monthlyAmount', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('renewalDate', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenantId'], ['Tenant.id'], name='Subscription_tenantId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='Subscription_pkey')
    )
    op.create_index('Subscription_tenantId_product_key', 'Subscription', ['tenantId', 'product'], unique=True)
    op.create_index('Subscription_tenantId_idx', 'Subscription', ['tenantId'], unique=False)
    op.create_index('Subscription_status_idx', 'Subscription', ['status'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('clients_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='clients_pkey'),
    sa.UniqueConstraint('email', name='clients_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_clients_id', 'clients', ['id'], unique=False)
    op.create_table('super_admin_organization_products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('enabled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='super_admin_organization_products_organization_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['super_admin_products.id'], name='super_admin_organization_products_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='super_admin_organization_products_pkey')
    )
    op.create_index('ix_super_admin_organization_products_id', 'super_admin_organization_products', ['id'], unique=False)
    op.create_table('User',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tenantId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('firstName', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('lastName', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('passwordHash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('isActive', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('isEmailVerified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenantId'], ['Tenant.id'], name='User_tenantId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='User_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('User_tenantId_idx', 'User', ['tenantId'], unique=False)
    op.create_index('User_tenantId_email_key', 'User', ['tenantId', 'email'], unique=True)
    op.create_table('ApprovalAction',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('workflowId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tenantId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('actorId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('action', postgresql.ENUM('REQUESTED', 'APPROVED', 'REJECTED', 'ESCALATED', 'REASSIGNED', 'COMMENTED', name='ApprovalActionType'), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actorId'], ['User.id'], name='ApprovalAction_actorId_fkey', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflowId'], ['ApprovalWorkflow.id'], name='ApprovalAction_workflowId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='ApprovalAction_pkey')
    )
    op.create_index('ApprovalAction_workflowId_idx', 'ApprovalAction', ['workflowId'], unique=False)
    op.create_index('ApprovalAction_tenantId_idx', 'ApprovalAction', ['tenantId'], unique=False)
    op.create_index('ApprovalAction_actorId_idx', 'ApprovalAction', ['actorId'], unique=False)
    op.create_table('invoice_lines',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('total', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name='invoice_lines_invoice_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='invoice_lines_pkey')
    )
    op.create_index('ix_invoice_lines_id', 'invoice_lines', ['id'], unique=False)
    op.create_table('compliance_policies',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('compliance_policies_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('HR', 'SECURITY', 'FINANCE', 'OPERATIONS', 'LEGAL', 'OTHER', name='policycategory'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'ACTIVE', 'ARCHIVED', name='policystatus'), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('effective_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('review_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], name='compliance_policies_created_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='compliance_policies_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_compliance_policies_id', 'compliance_policies', ['id'], unique=False)
    op.create_table('ZoikoCoreXWorkflow',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tenantId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('workflowKey', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('integrationName', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('executions', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('failures', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('HEALTHY', 'DEGRADED', 'FAILED', 'PAUSED', name='WorkflowStatus'), server_default=sa.text('\'HEALTHY\'::"WorkflowStatus"'), autoincrement=False, nullable=False),
    sa.Column('lastRunAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenantId'], ['Tenant.id'], name='ZoikoCoreXWorkflow_tenantId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='ZoikoCoreXWorkflow_pkey')
    )
    op.create_index('ZoikoCoreXWorkflow_tenantId_workflowKey_key', 'ZoikoCoreXWorkflow', ['tenantId', 'workflowKey'], unique=True)
    op.create_index('ZoikoCoreXWorkflow_tenantId_idx', 'ZoikoCoreXWorkflow', ['tenantId'], unique=False)
    op.create_index('ZoikoCoreXWorkflow_status_idx', 'ZoikoCoreXWorkflow', ['status'], unique=False)
    op.create_table('policy_acknowledgements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('policy_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('acknowledged_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='policy_acknowledgements_employee_id_fkey'),
    sa.ForeignKeyConstraint(['policy_id'], ['compliance_policies.id'], name='policy_acknowledgements_policy_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='policy_acknowledgements_pkey')
    )
    op.create_index('ix_policy_acknowledgements_id', 'policy_acknowledgements', ['id'], unique=False)
    op.create_table('AuditLog',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tenantId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('resourceType', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('resourceId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resourceName', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ipAddress', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('userAgent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('eventType', postgresql.ENUM('LOGIN', 'LOGOUT', 'USER_CHANGE', 'TENANT_CHANGE', 'ORGANIZATION_CHANGE', 'PAYROLL_EVENT', 'COMPLIANCE_EVENT', 'BILLING_EVENT', 'SECURITY_EVENT', 'SYSTEM_EVENT', name='AuditEventType'), server_default=sa.text('\'SYSTEM_EVENT\'::"AuditEventType"'), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('AUTHENTICATION', 'AUTHORIZATION', 'GOVERNANCE', 'PAYROLL', 'COMPLIANCE', 'BILLING', 'SECURITY', 'SYSTEM', name='AuditCategory'), server_default=sa.text('\'SYSTEM\'::"AuditCategory"'), autoincrement=False, nullable=False),
    sa.Column('outcome', postgresql.ENUM('SUCCESS', 'FAILURE', 'DENIED', 'PENDING', name='AuditOutcome'), server_default=sa.text('\'SUCCESS\'::"AuditOutcome"'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenantId'], ['Tenant.id'], name='AuditLog_tenantId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name='AuditLog_userId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='AuditLog_pkey')
    )
    op.create_index('AuditLog_userId_idx', 'AuditLog', ['userId'], unique=False)
    op.create_index('AuditLog_tenantId_idx', 'AuditLog', ['tenantId'], unique=False)
    op.create_index('AuditLog_eventType_idx', 'AuditLog', ['eventType'], unique=False)
    op.create_index('AuditLog_createdAt_idx', 'AuditLog', ['createdAt'], unique=False)
    op.create_index('AuditLog_category_idx', 'AuditLog', ['category'], unique=False)
    op.create_table('super_admin_platform_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_encrypted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='super_admin_platform_settings_pkey'),
    sa.UniqueConstraint('key', name='super_admin_platform_settings_key_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_super_admin_platform_settings_id', 'super_admin_platform_settings', ['id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('reports_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('report_type', postgresql.ENUM('HR', 'PAYROLL', 'BILLING', 'TIME', 'COMPLY', 'CUSTOM', name='reporttype'), autoincrement=False, nullable=False),
    sa.Column('filters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], name='reports_created_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='reports_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_reports_id', 'reports', ['id'], unique=False)
    op.create_table('_prisma_migrations',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('migration_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('logs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rolled_back_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('applied_steps_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='_prisma_migrations_pkey')
    )
    op.create_table('UserRole',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tenantId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('roleId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('assignedAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('assignedById', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['roleId'], ['Role.id'], name='UserRole_roleId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name='UserRole_userId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='UserRole_pkey')
    )
    op.create_index('UserRole_userId_roleId_key', 'UserRole', ['userId', 'roleId'], unique=True)
    op.create_index('UserRole_tenantId_idx', 'UserRole', ['tenantId'], unique=False)
    op.create_index('UserRole_roleId_idx', 'UserRole', ['roleId'], unique=False)
    op.create_table('super_admin_audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('action', postgresql.ENUM('CREATE', 'UPDATE', 'DELETE', 'SUSPEND', 'ACTIVATE', 'LOGIN', 'LOGOUT', 'CONFIG_CHANGE', name='auditaction'), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('performed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('performed_by_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['performed_by'], ['employees.id'], name='super_admin_audit_logs_performed_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='super_admin_audit_logs_pkey')
    )
    op.create_index('ix_super_admin_audit_logs_id', 'super_admin_audit_logs', ['id'], unique=False)
    op.create_table('ApprovalWorkflow',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tenantId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('workflowType', postgresql.ENUM('PAYROLL_APPROVAL', 'COMPLIANCE_APPROVAL', 'SUBSCRIPTION_APPROVAL', 'TENANT_ACTIVATION_APPROVAL', name='ApprovalWorkflowType'), autoincrement=False, nullable=False),
    sa.Column('resourceType', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('resourceId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('state', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'ESCALATED', 'CANCELED', name='ApprovalState'), server_default=sa.text('\'PENDING\'::"ApprovalState"'), autoincrement=False, nullable=False),
    sa.Column('requestedById', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('currentApproverId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('escalationLevel', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('escalatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('dueAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('completedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['currentApproverId'], ['User.id'], name='ApprovalWorkflow_currentApproverId_fkey', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenantId'], ['Tenant.id'], name='ApprovalWorkflow_tenantId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='ApprovalWorkflow_pkey')
    )
    op.create_index('ApprovalWorkflow_workflowType_idx', 'ApprovalWorkflow', ['workflowType'], unique=False)
    op.create_index('ApprovalWorkflow_tenantId_idx', 'ApprovalWorkflow', ['tenantId'], unique=False)
    op.create_index('ApprovalWorkflow_state_idx', 'ApprovalWorkflow', ['state'], unique=False)
    op.create_table('payslip_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('payroll_run_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('basic_salary', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('allowances', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('deductions', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('tax', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('gross_pay', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('net_pay', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('is_paid', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('paid_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='payslip_items_employee_id_fkey'),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.id'], name='payslip_items_payroll_run_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='payslip_items_pkey')
    )
    op.create_index('ix_payslip_items_id', 'payslip_items', ['id'], unique=False)
    op.create_table('ZoikoPayTransaction',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tenantId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('reference', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.TEXT(), server_default=sa.text("'USD'::text"), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'SUCCESSFUL', 'FAILED', 'REVERSED', name='ZoikoPayTransactionStatus'), server_default=sa.text('\'PENDING\'::"ZoikoPayTransactionStatus"'), autoincrement=False, nullable=False),
    sa.Column('settlementStatus', postgresql.ENUM('PENDING', 'SETTLED', 'DELAYED', 'FAILED', name='SettlementStatus'), server_default=sa.text('\'PENDING\'::"SettlementStatus"'), autoincrement=False, nullable=False),
    sa.Column('processedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenantId'], ['Tenant.id'], name='ZoikoPayTransaction_tenantId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='ZoikoPayTransaction_pkey')
    )
    op.create_index('ZoikoPayTransaction_tenantId_reference_key', 'ZoikoPayTransaction', ['tenantId', 'reference'], unique=True)
    op.create_index('ZoikoPayTransaction_tenantId_idx', 'ZoikoPayTransaction', ['tenantId'], unique=False)
    op.create_index('ZoikoPayTransaction_status_idx', 'ZoikoPayTransaction', ['status'], unique=False)
    op.create_table('Tenant',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'SUSPENDED', 'DELETED', name='TenantStatus'), server_default=sa.text('\'ACTIVE\'::"TenantStatus"'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Tenant_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('Tenant_slug_key', 'Tenant', ['slug'], unique=True)
    op.create_table('ComplianceReport',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tenantId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('packName', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('jurisdiction', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('alerts', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('violations', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('COMPLIANT', 'WATCHLIST', 'VIOLATION', 'REMEDIATION', name='ComplianceStatus'), server_default=sa.text('\'COMPLIANT\'::"ComplianceStatus"'), autoincrement=False, nullable=False),
    sa.Column('reviewedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenantId'], ['Tenant.id'], name='ComplianceReport_tenantId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='ComplianceReport_pkey')
    )
    op.create_index('ComplianceReport_tenantId_idx', 'ComplianceReport', ['tenantId'], unique=False)
    op.create_index('ComplianceReport_status_idx', 'ComplianceReport', ['status'], unique=False)
    op.create_table('report_runs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('run_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('format', postgresql.ENUM('JSON', 'CSV', 'PDF', name='reportformat'), autoincrement=False, nullable=True),
    sa.Column('result_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('row_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ran_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name='report_runs_report_id_fkey'),
    sa.ForeignKeyConstraint(['run_by'], ['employees.id'], name='report_runs_run_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='report_runs_pkey')
    )
    op.create_index('ix_report_runs_id', 'report_runs', ['id'], unique=False)
    op.create_table('GovernancePolicy',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tenantId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('domain', postgresql.ENUM('RBAC', 'PAYROLL', 'COMPLIANCE', 'BILLING', 'SECURITY', 'DATA_RETENTION', name='GovernanceDomain'), autoincrement=False, nullable=False),
    sa.Column('enforcement', postgresql.ENUM('MONITOR', 'WARN', 'BLOCK', name='EnforcementMode'), server_default=sa.text('\'MONITOR\'::"EnforcementMode"'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ENABLED', 'DISABLED', 'REVIEW_REQUIRED', name='GovernanceStatus'), server_default=sa.text('\'ENABLED\'::"GovernanceStatus"'), autoincrement=False, nullable=False),
    sa.Column('exceptions', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenantId'], ['Tenant.id'], name='GovernancePolicy_tenantId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='GovernancePolicy_pkey')
    )
    op.create_index('GovernancePolicy_tenantId_name_key', 'GovernancePolicy', ['tenantId', 'name'], unique=True)
    op.create_index('GovernancePolicy_tenantId_idx', 'GovernancePolicy', ['tenantId'], unique=False)
    op.create_index('GovernancePolicy_domain_idx', 'GovernancePolicy', ['domain'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('invoice_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'SENT', 'PAID', 'OVERDUE', 'CANCELLED', name='invoicestatus'), autoincrement=False, nullable=True),
    sa.Column('issue_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('subtotal', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('tax_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='invoices_client_id_fkey'),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], name='invoices_created_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='invoices_pkey'),
    sa.UniqueConstraint('invoice_number', name='invoices_invoice_number_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_invoices_id', 'invoices', ['id'], unique=False)
    op.create_table('Role',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tenantId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('key', postgresql.ENUM('SUPER_ADMIN', 'PLATFORM_ADMIN', 'TENANT_ADMIN', 'HR_ADMIN', 'PAYROLL_ADMIN', 'COMPLIANCE_ADMIN', 'AUDITOR', name='RoleKey'), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('isSystem', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenantId'], ['Tenant.id'], name='Role_tenantId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='Role_pkey')
    )
    op.create_index('Role_tenantId_key_key', 'Role', ['tenantId', 'key'], unique=True)
    op.create_index('Role_tenantId_idx', 'Role', ['tenantId'], unique=False)
    op.create_table('UserPermission',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tenantId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('permissionId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('assignedAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('assignedById', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['permissionId'], ['Permission.id'], name='UserPermission_permissionId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name='UserPermission_userId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='UserPermission_pkey')
    )
    op.create_index('UserPermission_userId_permissionId_key', 'UserPermission', ['userId', 'permissionId'], unique=True)
    op.create_index('UserPermission_tenantId_idx', 'UserPermission', ['tenantId'], unique=False)
    op.create_index('UserPermission_permissionId_idx', 'UserPermission', ['permissionId'], unique=False)
    op.create_table('PayrollRun',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tenantId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('runCode', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('scheduleName', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('payPeriod', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('grossAmount', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('employeeCount', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('approvalsPending', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'PROCESSING', 'COMPLETED', 'FAILED', 'CORRECTION_REQUIRED', name='PayrollRunStatus'), server_default=sa.text('\'PENDING_APPROVAL\'::"PayrollRunStatus"'), autoincrement=False, nullable=False),
    sa.Column('failureReason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('processedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenantId'], ['Tenant.id'], name='PayrollRun_tenantId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='PayrollRun_pkey')
    )
    op.create_index('PayrollRun_tenantId_runCode_key', 'PayrollRun', ['tenantId', 'runCode'], unique=True)
    op.create_index('PayrollRun_tenantId_idx', 'PayrollRun', ['tenantId'], unique=False)
    op.create_index('PayrollRun_status_idx', 'PayrollRun', ['status'], unique=False)
    op.create_table('super_admin_subscriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('plan_type', postgresql.ENUM('TRIAL', 'FREE', 'BASIC', 'PROFESSIONAL', 'ENTERPRISE', name='plantype'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'EXPIRED', 'CANCELLED', 'PENDING', name='subscriptionstatus'), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('max_users', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_storage_gb', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='super_admin_subscriptions_organization_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='super_admin_subscriptions_pkey'),
    sa.UniqueConstraint('organization_id', name='super_admin_subscriptions_organization_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_super_admin_subscriptions_id', 'super_admin_subscriptions', ['id'], unique=False)
    op.create_table('super_admin_system_health',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('component', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('HEALTHY', 'DEGRADED', 'DOWN', name='healthstatus'), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('response_time_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('checked_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='super_admin_system_health_pkey')
    )
    op.create_index('ix_super_admin_system_health_id', 'super_admin_system_health', ['id'], unique=False)
    op.create_table('Organization',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tenantId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('plan', postgresql.ENUM('TRIAL', 'PREMIUM', 'ENTERPRISE', name='Plan'), server_default=sa.text('\'ENTERPRISE\'::"Plan"'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'PENDING', 'SUSPENDED', 'DELETED', name='OrganizationStatus'), server_default=sa.text('\'ACTIVE\'::"OrganizationStatus"'), autoincrement=False, nullable=False),
    sa.Column('employeesCount', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenantId'], ['Tenant.id'], name='Organization_tenantId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='Organization_pkey')
    )
    op.create_index('Organization_tenantId_name_key', 'Organization', ['tenantId', 'name'], unique=True)
    op.create_index('Organization_tenantId_idx', 'Organization', ['tenantId'], unique=False)
    op.create_table('time_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('clock_in', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('clock_out', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('work_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_approved', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='time_entries_employee_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='time_entries_pkey')
    )
    op.create_index('ix_time_entries_id', 'time_entries', ['id'], unique=False)
    op.create_table('super_admin_products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('icon', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', 'MAINTENANCE', name='productstatus'), autoincrement=False, nullable=False),
    sa.Column('is_core', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='super_admin_products_pkey'),
    sa.UniqueConstraint('code', name='super_admin_products_code_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_super_admin_products_id', 'super_admin_products', ['id'], unique=False)
    op.create_table('payroll_runs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('period_label', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('period_start', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('period_end', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PROCESSING', 'COMPLETED', 'PAID', name='payrollstatus'), autoincrement=False, nullable=True),
    sa.Column('total_gross', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_net', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], name='payroll_runs_created_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='payroll_runs_pkey')
    )
    op.create_index('ix_payroll_runs_id', 'payroll_runs', ['id'], unique=False)
    # ### end Alembic commands ###
