const BILLING = "/billing";

export const ENDPOINTS = {
  SETTINGS: `${BILLING}/settings`,
  SETTINGS_CONFIG: `${BILLING}/settings/config`,
  SETTINGS_CONFIG_RESET: `${BILLING}/settings/config/reset`,
  SETTINGS_CONFIG_VALIDATE: `${BILLING}/settings/config/validate`,
  SETTINGS_EXCHANGE_RATES: `${BILLING}/settings/exchange-rates`,
  SETTINGS_EXCHANGE_RATES_REFRESH: `${BILLING}/settings/exchange-rates/refresh`,
  SETTINGS_EXCHANGE_RATES_PAIR: `${BILLING}/settings/exchange-rates/pair`,
  SETTINGS_EXCHANGE_RATES_SUPPORTED: `${BILLING}/settings/exchange-rates/supported`,
  DASHBOARD: `${BILLING}/dashboard`,
  DASHBOARD_KPIS: `${BILLING}/dashboard/kpis`,
  DASHBOARD_REVENUE: `${BILLING}/dashboard/revenue`,
  DASHBOARD_PAYMENT_TREND: `${BILLING}/dashboard/payment-trend`,

  CUSTOMERS: `${BILLING}/customers`,
  CUSTOMER: (id) => `${BILLING}/customers/${id}`,
  CUSTOMER_SEARCH: `${BILLING}/customers/search`,
  CUSTOMER_HARD_DELETE: (id) => `${BILLING}/customers/${id}/hard-delete`,
  CUSTOMER_RESTORE: (id) => `${BILLING}/customers/${id}/restore`,
  CUSTOMER_BULK_DELETE: `${BILLING}/customers/bulk-delete`,
  CUSTOMER_BULK_STATUS: `${BILLING}/customers/bulk-status`,
  CUSTOMER_EXPORT: `${BILLING}/customers/export`,
  CUSTOMER_IMPORT: `${BILLING}/customers/import`,
  CUSTOMER_ACTIVITY: (id) => `${BILLING}/customers/${id}/activity`,
  CUSTOMER_CONTACTS: (id) => `${BILLING}/customers/${id}/contacts`,
  CUSTOMER_CONTACT: (cid, contactId) => `${BILLING}/customers/${cid}/contacts/${contactId}`,
  CUSTOMER_CONTACT_PRIMARY: (cid, contactId) => `${BILLING}/customers/${cid}/contacts/${contactId}/primary`,
  CUSTOMER_KPI: `${BILLING}/customers/kpi`,
  CUSTOMER_CREDIT_BALANCE: (id) => `${BILLING}/customers/${id}/credit-balance`,
  CUSTOMER_DOCUMENTS: (id) => `${BILLING}/customers/${id}/documents`,
  CUSTOMER_DOCUMENT: (cid, docId) => `${BILLING}/customers/${cid}/documents/${docId}`,
  CUSTOMER_NOTES: (id) => `${BILLING}/customers/${id}/notes`,
  CUSTOMER_NOTE: (cid, noteId) => `${BILLING}/customers/${cid}/notes/${noteId}`,
  CUSTOMER_ACTIVATE: (id) => `${BILLING}/customers/${id}/activate`,
  CUSTOMER_DEACTIVATE: (id) => `${BILLING}/customers/${id}/deactivate`,
  CUSTOMER_SUSPEND: (id) => `${BILLING}/customers/${id}/suspend`,
  CUSTOMER_ANALYTICS: (id) => `${BILLING}/customers/${id}/analytics`,
  CUSTOMER_IMPORT_FILE: `${BILLING}/customers/import/file`,

  PRODUCT_CATEGORIES: `${BILLING}/products/categories`,
  PRODUCT_CATEGORY: (id) => `${BILLING}/products/categories/${id}`,
  PRODUCT_CATEGORY_CHILDREN: (id) => `${BILLING}/products/categories/${id}/children`,
  PRODUCTS: `${BILLING}/products`,
  PRODUCT_SUBSCRIBABLE: `${BILLING}/products/subscribable`,
  PRODUCT_USAGE_BILLABLE: `${BILLING}/products/usage-billable`,
  PRODUCT_BULK_STATUS: `${BILLING}/products/bulk-status`,
  PRODUCT_BULK_DELETE: `${BILLING}/products/bulk-delete`,
  PRODUCT: (id) => `${BILLING}/products/${id}`,
  PRODUCT_RESTORE: (id) => `${BILLING}/products/${id}/restore`,
  PRODUCT_DUPLICATE: (id) => `${BILLING}/products/${id}/duplicate`,
  PRODUCT_IMPORT_PREVIEW: `${BILLING}/products/import/preview`,
  PRODUCT_IMPORT_CONFIRM: `${BILLING}/products/import/confirm`,
  PRODUCT_IMPORT_TEMPLATE: `${BILLING}/products/import/template`,
  PRODUCT_EXPORT: `${BILLING}/products/export`,

  PRICING_PLANS: `${BILLING}/pricing-plans`,
  PRICING_PLANS_RESOLVE: `${BILLING}/pricing-plans/resolve`,
  PRICING_PLANS_BY_PRODUCT: (id) => `${BILLING}/pricing-plans/by-product/${id}`,
  PRICING_PLAN: (id) => `${BILLING}/pricing-plans/${id}`,
  PRICING_PLAN_TIERS: (id) => `${BILLING}/pricing-plans/${id}/tiers`,
  PRICING_PLAN_TIER: (pid, tid) => `${BILLING}/pricing-plans/${pid}/tiers/${tid}`,

  PRICE_LISTS: `${BILLING}/price-lists`,
  PRICE_LIST: (id) => `${BILLING}/price-lists/${id}`,
  PRICE_LIST_DEFAULT: `${BILLING}/price-lists/default`,
  PRICE_LIST_ITEMS: (id) => `${BILLING}/price-lists/${id}/items`,
  PRICE_LIST_ITEM: (pid, iid) => `${BILLING}/price-lists/${pid}/items/${iid}`,

  PRICING_RULES: `${BILLING}/pricing-rules`,
  PRICING_RULES_APPLICABLE: `${BILLING}/pricing-rules/applicable`,
  PRICING_RULE: (id) => `${BILLING}/pricing-rules/${id}`,
  PRICING_RULE_TIERS: (id) => `${BILLING}/pricing-rules/${id}/tiers`,
  PRICING_RULE_TIER: (pid, tid) => `${BILLING}/pricing-rules/${pid}/tiers/${tid}`,

  DISCOUNTS: `${BILLING}/discounts`,
  DISCOUNTS_VALID_FOR_ORDER: `${BILLING}/discounts/valid-for-order`,
  DISCOUNT: (id) => `${BILLING}/discounts/${id}`,
  DISCOUNT_USAGE: (id) => `${BILLING}/discounts/${id}/usage`,
  DISCOUNT_USAGE_COUNT: (id) => `${BILLING}/discounts/${id}/usage-count`,

  CURRENCY_PRICING: `${BILLING}/currency-pricing`,
  CURRENCY_PRICING_BY_PRODUCT: (id) => `${BILLING}/currency-pricing/by-product/${id}`,
  CURRENCY_PRICING_ITEM: (id) => `${BILLING}/currency-pricing/${id}`,

  TAX_PRICING: `${BILLING}/tax-pricing`,
  TAX_PRICING_APPLICABLE: `${BILLING}/tax-pricing/applicable`,
  TAX_PRICING_ITEM: (id) => `${BILLING}/tax-pricing/${id}`,
  TAX_GROUPS: `${BILLING}/tax-pricing/groups`,
  TAX_GROUP: (id) => `${BILLING}/tax-pricing/groups/${id}`,
  TAX_GROUP_MEMBERS: (id) => `${BILLING}/tax-pricing/groups/${id}/members`,
  TAX_GROUP_MEMBER: (id) => `${BILLING}/tax-pricing/groups/members/${id}`,

  CONTRACTS: `${BILLING}/contracts`,
  CONTRACTS_ACTIVE: `${BILLING}/contracts/active`,
  CONTRACTS_EXPIRING: `${BILLING}/contracts/expiring`,
  CONTRACTS_SUMMARY: `${BILLING}/contracts/summary`,
  CONTRACT: (id) => `${BILLING}/contracts/${id}`,
  CONTRACT_ACTIVATE: (id) => `${BILLING}/contracts/${id}/activate`,
  CONTRACT_TERMINATE: (id) => `${BILLING}/contracts/${id}/terminate`,
  CONTRACT_CANCEL: (id) => `${BILLING}/contracts/${id}/cancel`,
  CONTRACT_RENEW: (id) => `${BILLING}/contracts/${id}/renew`,
  CONTRACT_ITEMS: (id) => `${BILLING}/contracts/${id}/items`,
  CONTRACT_CONVERT_FROM_QUOTATION: `${BILLING}/contracts/convert-from-quotation`,
  CONTRACT_GENERATE_INVOICE: (id) => `${BILLING}/contracts/${id}/generate-invoice`,
  CONTRACT_AMENDMENTS: (id) => `${BILLING}/contracts/${id}/amendments`,

  QUOTATIONS: `${BILLING}/quotations`,
  QUOTATION: (id) => `${BILLING}/quotations/${id}`,
  QUOTATION_ITEMS: (id) => `${BILLING}/quotations/${id}/items`,
  QUOTATION_ITEM: (quoteId, itemId) => `${BILLING}/quotations/${quoteId}/items/${itemId}`,
  QUOTATION_SEND: (id) => `${BILLING}/quotations/${id}/send`,
  QUOTATION_ACCEPT: (id) => `${BILLING}/quotations/${id}/accept`,
  QUOTATION_REJECT: (id) => `${BILLING}/quotations/${id}/reject`,
  QUOTATION_CANCEL: (id) => `${BILLING}/quotations/${id}/cancel`,
  QUOTATION_CONVERT: (id) => `${BILLING}/quotations/${id}/convert-to-invoice`,
  QUOTATION_RECALCULATE: (id) => `${BILLING}/quotations/${id}/recalculate`,
  QUOTATION_DUPLICATE: (id) => `${BILLING}/quotations/${id}/duplicate`,

  SUBSCRIPTION_PLANS: `${BILLING}/subscriptions/plans`,
  SUBSCRIPTION_PLANS_PUBLIC: `${BILLING}/subscriptions/plans/public`,
  SUBSCRIPTION_PLAN: (id) => `${BILLING}/subscriptions/plans/${id}`,
  SUBSCRIPTIONS: `${BILLING}/subscriptions`,
  SUBSCRIPTIONS_ACTIVE: `${BILLING}/subscriptions/active`,
  SUBSCRIPTIONS_SUMMARY: `${BILLING}/subscriptions/summary`,
  SUBSCRIPTION: (id) => `${BILLING}/subscriptions/${id}`,
  SUBSCRIPTION_ACTIVATE: (id) => `${BILLING}/subscriptions/${id}/activate`,
  SUBSCRIPTION_PAUSE: (id) => `${BILLING}/subscriptions/${id}/pause`,
  SUBSCRIPTION_CANCEL: (id) => `${BILLING}/subscriptions/${id}/cancel`,
  SUBSCRIPTION_RESUME: (id) => `${BILLING}/subscriptions/${id}/resume`,
  SUBSCRIPTION_RENEW: (id) => `${BILLING}/subscriptions/${id}/renew`,
  SUBSCRIPTION_CHANGE_PLAN: (id) => `${BILLING}/subscriptions/${id}/change-plan`,
  SUBSCRIPTION_EVENTS: (id) => `${BILLING}/subscriptions/${id}/events`,
  SUBSCRIPTION_REPORTING: `${BILLING}/subscriptions/reporting`,
  SUBSCRIPTION_PROCESS_BILLING: `${BILLING}/subscriptions/process-billing`,
  SUBSCRIPTION_GENERATE_INVOICE: (id) => `${BILLING}/subscriptions/${id}/generate-invoice`,

  INVOICES: `${BILLING}/invoices`,
  INVOICES_OVERDUE: `${BILLING}/invoices/overdue`,
  INVOICES_OUTSTANDING_TOTAL: `${BILLING}/invoices/outstanding-total`,
  INVOICES_DASHBOARD_STATS: `${BILLING}/invoices/dashboard-stats`,
  INVOICES_DUE_BETWEEN: `${BILLING}/invoices/due-between`,
  INVOICES_ENTERPRISE_DASHBOARD: `${BILLING}/invoices/enterprise-dashboard`,
  INVOICES_INVOICE_TREND: `${BILLING}/invoices/invoice-trend`,
  INVOICES_REVENUE_TREND: `${BILLING}/invoices/revenue-trend`,
  INVOICES_PAYMENT_COLLECTION_TREND: `${BILLING}/invoices/payment-collection-trend`,
  INVOICES_STATUS_DISTRIBUTION: `${BILLING}/invoices/status-distribution`,
  INVOICES_MONTHLY_REVENUE: `${BILLING}/invoices/monthly-revenue`,
  INVOICES_RECENT_ACTIVITY: `${BILLING}/invoices/recent-activity`,
  INVOICES_BULK_DELETE: `${BILLING}/invoices/bulk-delete`,
  INVOICE: (id) => `${BILLING}/invoices/${id}`,
  INVOICE_FINALIZE: (id) => `${BILLING}/invoices/${id}/finalize`,
  INVOICE_SEND: (id) => `${BILLING}/invoices/${id}/send`,
  INVOICE_SEND_EMAIL: (id) => `${BILLING}/invoices/${id}/send-email`,
  INVOICE_CANCEL: (id) => `${BILLING}/invoices/${id}/cancel`,
  INVOICE_VOID: (id) => `${BILLING}/invoices/${id}/void`,
  INVOICE_RECALCULATE: (id) => `${BILLING}/invoices/${id}/recalculate`,
  INVOICE_ITEMS: (id) => `${BILLING}/invoices/${id}/items`,
  INVOICE_STATUS_HISTORY: (id) => `${BILLING}/invoices/${id}/status-history`,
  INVOICE_COMMUNICATIONS: (id) => `${BILLING}/invoices/${id}/communications`,
  INVOICE_TIMELINE: (id) => `${BILLING}/invoices/${id}/timeline`,

  PAYMENT_METHODS: `${BILLING}/payments/methods`,
  PAYMENT_METHODS_BY_CUSTOMER: (id) => `${BILLING}/payments/methods/customer/${id}`,
  PAYMENT_METHOD: (id) => `${BILLING}/payments/methods/${id}`,
  PAYMENT_METHOD_DEFAULT: (id) => `${BILLING}/payments/methods/${id}/default`,
  PAYMENTS: `${BILLING}/payments`,
  PAYMENTS_TOTAL_COLLECTED: `${BILLING}/payments/total-collected`,
  PAYMENT: (id) => `${BILLING}/payments/${id}`,
  PAYMENT_STATUS: (id) => `${BILLING}/payments/${id}/status`,
  PAYMENT_ALLOCATE: (id) => `${BILLING}/payments/${id}/allocate`,
  PAYMENT_ALLOCATIONS: (id) => `${BILLING}/payments/${id}/allocations`,
  PAYMENT_ATTEMPTS: (id) => `${BILLING}/payments/${id}/attempts`,
  PAYMENT_RECONCILE: (id) => `${BILLING}/payments/${id}/reconcile`,
  PAYMENT_UNALLOCATED: `${BILLING}/payments/unallocated`,
  PAYMENT_UNALLOCATED_AMOUNT: (id) => `${BILLING}/payments/${id}/unallocated-amount`,
  PAYMENT_ALLOCATION_DELETE: (id) => `${BILLING}/payments/allocations/${id}`,
  CUSTOMER_STATEMENT: (id) => `${BILLING}/customers/${id}/statement`,

  TAX_RATES: `${BILLING}/tax-rates`,
  TAX_RATES_APPLICABLE: `${BILLING}/tax-rates/applicable`,
  TAX_RATES_SUMMARY: `${BILLING}/tax-rates/summary`,
  TAX_RATES_CALCULATE: `${BILLING}/tax-rates/calculate`,
  TAX_RATES_DEFAULT: `${BILLING}/tax-rates/default`,
  TAX_RATE: (id) => `${BILLING}/tax-rates/${id}`,

  CREDIT_NOTES: `${BILLING}/credit-notes`,
  CREDIT_NOTES_OUTSTANDING: `${BILLING}/credit-notes/outstanding`,
  CREDIT_NOTES_DASHBOARD_STATS: `${BILLING}/credit-notes/dashboard-stats`,
  CREDIT_NOTES_STATUS_DISTRIBUTION: `${BILLING}/credit-notes/status-distribution`,
  CREDIT_NOTES_TYPE_DISTRIBUTION: `${BILLING}/credit-notes/type-distribution`,
  CREDIT_NOTES_MONTHLY_TREND: `${BILLING}/credit-notes/monthly-trend`,
  CREDIT_NOTES_CUSTOMER_BALANCE: (customerId) => `${BILLING}/credit-notes/customer-balance/${customerId}`,
  CREDIT_NOTES_BULK_DELETE: `${BILLING}/credit-notes/bulk-delete`,
  CREDIT_NOTE: (id) => `${BILLING}/credit-notes/${id}`,
  CREDIT_NOTE_APPROVE: (id) => `${BILLING}/credit-notes/${id}/approve`,
  CREDIT_NOTE_ISSUE: (id) => `${BILLING}/credit-notes/${id}/issue`,
  CREDIT_NOTE_SEND_EMAIL: (id) => `${BILLING}/credit-notes/${id}/send-email`,
  CREDIT_NOTE_VOID: (id) => `${BILLING}/credit-notes/${id}/void`,
  CREDIT_NOTE_APPLY: (id) => `${BILLING}/credit-notes/${id}/apply`,
  CREDIT_NOTE_APPLICATIONS: (id) => `${BILLING}/credit-notes/${id}/applications`,
  CREDIT_NOTE_STATUS_HISTORY: (id) => `${BILLING}/credit-notes/${id}/status-history`,
  CREDIT_NOTE_COMMUNICATIONS: (id) => `${BILLING}/credit-notes/${id}/communications`,
  CREDIT_NOTE_TIMELINE: (id) => `${BILLING}/credit-notes/${id}/timeline`,

  REFUNDS: `${BILLING}/refunds`,
  REFUNDS_DASHBOARD_STATS: `${BILLING}/refunds/dashboard-stats`,
  REFUNDS_STATUS_DISTRIBUTION: `${BILLING}/refunds/status-distribution`,
  REFUNDS_TYPE_DISTRIBUTION: `${BILLING}/refunds/type-distribution`,
  REFUNDS_METHOD_DISTRIBUTION: `${BILLING}/refunds/method-distribution`,
  REFUNDS_SOURCE_DISTRIBUTION: `${BILLING}/refunds/source-distribution`,
  REFUNDS_REASON_DISTRIBUTION: `${BILLING}/refunds/reason-distribution`,
  REFUNDS_MONTHLY_TREND: `${BILLING}/refunds/monthly-trend`,
  REFUNDS_BY_CUSTOMER: (customerId) => `${BILLING}/refunds/customer/${customerId}`,
  REFUNDS_CUSTOMER_SUMMARY: (customerId) => `${BILLING}/refunds/customer/${customerId}/summary`,
  REFUND: (id) => `${BILLING}/refunds/${id}`,
  REFUND_SUBMIT: (id) => `${BILLING}/refunds/${id}/submit`,
  REFUND_APPROVE: (id) => `${BILLING}/refunds/${id}/approve`,
  REFUND_REJECT: (id) => `${BILLING}/refunds/${id}/reject`,
  REFUND_CANCEL: (id) => `${BILLING}/refunds/${id}/cancel`,
  REFUND_PROCESS: (id) => `${BILLING}/refunds/${id}/process`,
  REFUND_COMPLETE: (id) => `${BILLING}/refunds/${id}/complete`,
  REFUND_FAIL: (id) => `${BILLING}/refunds/${id}/fail`,
  REFUND_SEND_EMAIL: (id) => `${BILLING}/refunds/${id}/send-email`,
  REFUND_STATUS_HISTORY: (id) => `${BILLING}/refunds/${id}/status-history`,
  REFUND_COMMUNICATIONS: (id) => `${BILLING}/refunds/${id}/communications`,
  REFUND_TIMELINE: (id) => `${BILLING}/refunds/${id}/timeline`,

  WRITE_OFFS: `${BILLING}/write-offs`,
  WRITE_OFFS_DASHBOARD_STATS: `${BILLING}/write-offs/dashboard-stats`,
  WRITE_OFFS_STATUS_DISTRIBUTION: `${BILLING}/write-offs/status-distribution`,
  WRITE_OFFS_TYPE_DISTRIBUTION: `${BILLING}/write-offs/type-distribution`,
  WRITE_OFFS_ADJUSTMENT_TYPE_DISTRIBUTION: `${BILLING}/write-offs/adjustment-type-distribution`,
  WRITE_OFFS_SOURCE_DISTRIBUTION: `${BILLING}/write-offs/source-distribution`,
  WRITE_OFFS_REASON_DISTRIBUTION: `${BILLING}/write-offs/reason-distribution`,
  WRITE_OFFS_CUSTOMER_DISTRIBUTION: `${BILLING}/write-offs/customer-distribution`,
  WRITE_OFFS_MONTHLY_TREND: `${BILLING}/write-offs/monthly-trend`,
  WRITE_OFFS_BY_CUSTOMER: (customerId) => `${BILLING}/write-offs/customer/${customerId}`,
  WRITE_OFFS_CUSTOMER_SUMMARY: (customerId) => `${BILLING}/write-offs/customer/${customerId}/summary`,
  WRITE_OFF: (id) => `${BILLING}/write-offs/${id}`,
  WRITE_OFF_SUBMIT: (id) => `${BILLING}/write-offs/${id}/submit`,
  WRITE_OFF_APPROVE: (id) => `${BILLING}/write-offs/${id}/approve`,
  WRITE_OFF_CANCEL: (id) => `${BILLING}/write-offs/${id}/cancel`,
  WRITE_OFF_EXECUTE: (id) => `${BILLING}/write-offs/${id}/execute`,
  WRITE_OFF_REVERSE: (id) => `${BILLING}/write-offs/${id}/reverse`,
  WRITE_OFF_SEND_EMAIL: (id) => `${BILLING}/write-offs/${id}/send-email`,
  WRITE_OFF_STATUS_HISTORY: (id) => `${BILLING}/write-offs/${id}/status-history`,
  WRITE_OFF_COMMUNICATIONS: (id) => `${BILLING}/write-offs/${id}/communications`,
  WRITE_OFF_TIMELINE: (id) => `${BILLING}/write-offs/${id}/timeline`,

  DUNNING_LEVELS: `${BILLING}/dunning/levels`,
  DUNNING_LEVEL: (id) => `${BILLING}/dunning/levels/${id}`,
  DUNNING_CASES: `${BILLING}/dunning/cases`,
  DUNNING_CASES_ACTIVE: `${BILLING}/dunning/cases/active`,
  DUNNING_CASE: (id) => `${BILLING}/dunning/cases/${id}`,
  DUNNING_CASE_ESCALATE: (id) => `${BILLING}/dunning/cases/${id}/escalate`,
  DUNNING_CASE_RESOLVE: (id) => `${BILLING}/dunning/cases/${id}/resolve`,
  DUNNING_CASE_CLOSE: (id) => `${BILLING}/dunning/cases/${id}/close`,
  DUNNING_SCHEDULE: `${BILLING}/dunning/schedule`,
  DUNNING_PROCESS: `${BILLING}/dunning/process`,
  DUNNING_DASHBOARD_STATS: `${BILLING}/dunning/dashboard-stats`,
  DUNNING_LEVEL_DISTRIBUTION: `${BILLING}/dunning/level-distribution`,
  DUNNING_CASE_STATUS_HISTORY: (id) => `${BILLING}/dunning/cases/${id}/status-history`,
  DUNNING_CASE_TIMELINE: (id) => `${BILLING}/dunning/cases/${id}/timeline`,

  COLLECTIONS_CASES: `${BILLING}/collections/cases`,
  COLLECTIONS_CASE: (id) => `${BILLING}/collections/cases/${id}`,
  COLLECTIONS_CASE_ASSIGN: (id) => `${BILLING}/collections/cases/${id}/assign`,
  COLLECTIONS_CASE_RESOLVE: (id) => `${BILLING}/collections/cases/${id}/resolve`,
  COLLECTIONS_CASE_CLOSE: (id) => `${BILLING}/collections/cases/${id}/close`,
  COLLECTIONS_CASE_ESCALATE: (id) => `${BILLING}/collections/cases/${id}/escalate`,
  COLLECTIONS_CASE_ACTIONS: (id) => `${BILLING}/collections/cases/${id}/actions`,
  COLLECTIONS_CASE_STATUS_HISTORY: (id) => `${BILLING}/collections/cases/${id}/status-history`,
  COLLECTIONS_CASE_TIMELINE: (id) => `${BILLING}/collections/cases/${id}/timeline`,
  COLLECTIONS_AGING: `${BILLING}/collections/aging`,
  COLLECTIONS_QUEUE: `${BILLING}/collections/queue`,
  COLLECTIONS_DASHBOARD_STATS: `${BILLING}/collections/dashboard-stats`,
  COLLECTIONS_PRIORITY_DISTRIBUTION: `${BILLING}/collections/priority-distribution`,
  COLLECTIONS_CUSTOMER_SUMMARY: (customerId) => `${BILLING}/collections/customers/${customerId}/summary`,
  COLLECTIONS_ESCALATE_OVERDUE: `${BILLING}/collections/escalate-overdue`,
  COLLECTIONS_REPORT_OVERDUE_BY_CUSTOMER: `${BILLING}/collections/reports/overdue-by-customer`,
  COLLECTIONS_REPORT_DUNNING_PERFORMANCE: `${BILLING}/collections/reports/dunning-performance`,
  COLLECTIONS_REPORT_EFFECTIVENESS: `${BILLING}/collections/reports/collection-effectiveness`,
  COLLECTIONS_REPORT_RECOVERY_TREND: `${BILLING}/collections/reports/recovery-trend`,

  PROMISES: `${BILLING}/promise-to-pay`,
  PROMISE: (id) => `${BILLING}/promise-to-pay/${id}`,
  PROMISE_MARK_FULFILLED: (id) => `${BILLING}/promise-to-pay/${id}/mark-fulfilled`,
  PROMISE_MARK_BROKEN: (id) => `${BILLING}/promise-to-pay/${id}/mark-broken`,
  PROMISE_CANCEL: (id) => `${BILLING}/promise-to-pay/${id}/cancel`,
  PROMISE_PROCESS: `${BILLING}/promise-to-pay/process`,
  PROMISE_SUCCESS_RATE: `${BILLING}/promise-to-pay/success-rate`,
  PROMISE_DASHBOARD_STATS: `${BILLING}/promise-to-pay/dashboard-stats`,
  PROMISE_BY_CUSTOMER: (customerId) => `${BILLING}/promise-to-pay/customer/${customerId}`,
  PROMISE_TIMELINE: (id) => `${BILLING}/promise-to-pay/${id}/timeline`,
  PROMISE_COMMUNICATIONS: (id) => `${BILLING}/promise-to-pay/${id}/communications`,

  REVENUE_SCHEDULES: `${BILLING}/revenue/schedules`,
  REVENUE_SCHEDULE: (id) => `${BILLING}/revenue/schedules/${id}`,
  REVENUE_SCHEDULE_RECOGNIZE: (id) => `${BILLING}/revenue/schedules/${id}/recognize`,
  REVENUE_SCHEDULE_ENTRIES: (id) => `${BILLING}/revenue/schedules/${id}/entries`,
  REVENUE_DEFERRED: `${BILLING}/revenue/deferred`,
  REVENUE_RECOGNIZE_ALL: `${BILLING}/revenue/recognize-all`,

  AUDIT_LOGS: `${BILLING}/audit-logs`,

  // ── Phase 5C.4: Admin / Diagnostics ──────────────────────────────────────
  SETTINGS_ADMIN_SMTP_TEST: `${BILLING}/settings/smtp/test`,
  SETTINGS_ADMIN_EMAIL_TEMPLATES: `${BILLING}/settings/email-templates`,
  SETTINGS_ADMIN_EMAIL_TEMPLATE_PREVIEW: (name) => `${BILLING}/settings/email-templates/${name}/preview`,
  SETTINGS_ADMIN_NUMBERING_DIAGNOSTICS: `${BILLING}/settings/numbering/diagnostics`,
  SETTINGS_ADMIN_TAX_DIAGNOSTICS: `${BILLING}/settings/tax/diagnostics`,
  SETTINGS_ADMIN_EXCHANGE_RATE_DIAGNOSTICS: `${BILLING}/settings/exchange-rates/diagnostics`,
  SETTINGS_ADMIN_HEALTH: `${BILLING}/settings/health`,
  SETTINGS_ADMIN_VALIDATE: `${BILLING}/settings/validate`,
};
